server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
mybatis:
  type-aliases-package: com.mutest.model
  mapper-locations: classpath:/mappers/*.xml